### ISSUE TITLE
Create an ns-vue-radio tool to easily build apps

### ISSUE THREAD

**Issue by sgobotta** [Cambalab/ns-vue-radio#105]
**Is your feature request related to a problem? Please describe.**
We're looking for a programmatic way to build ns-vue-radio applications. A bash or node script could help us generate a radio app based in a config file. 

**Describe the solution you'd like**
The program input woud be a text file or content from a request and the output would be an application.

Requirements:
+   get a google-services.json
+   create a keystore
+   images (splash, icon, logo)
+   config.json (or use the default)

Script Inputs:
+   google-services.json
+   Splash screen image
+   App icon image
+   Logo image
+   input file/json response

Script Exercise
+   A script fetches information from ~an API or~ a file with the app customisation data
+   The information is parsed to a config.js
+   Assets are processed (splash screen, app icon)
+   The google-services.json is placed in `app/App_Resources/Android/`
+   The script executes a command to build an .aab/.apk

**Describe alternatives you've considered**
A script written in node/bash

**Additional context/Feature requirements**

+   [x] Guide: write a how-to-use guide for the script - #118
+   [x] Guide: Provide design of the information ~fetched from an API~ read from file - #106
+   [x] Guide to generate a keystore - #119
+   [x] Guide to properly `Get your google-services.json`  - #117
+   [x] Guide: If the Splash Screen and/or the app icon is not a url, document where the assets must be placed so that the script knows where to move them. - #123

**When the tasks above are finished, issues regarding development features will be revelead below**

+   [x] Create Initial Script - #109
+   [x] Fetch data from ~an API~ file - #111
+   [x] Adapt API response to file output - #112

> EDIT: updates Scripts inputs section
> EDIT: updates 2nd feature item

**Last tasks**

+   [x] An application can be **built** and **installed** using either the **create-app** script or the `tns` command line scripts.
+   [x] An application can be **built** using data provided by a backend. The splash, logo, icons and color correspond to the ones in the provided configuration file.
+   [x] #139 should be approved and closed

**Comment by estefi-prieto** [comment]
The header image is hardcoded, we should consider this, it's currently [here](https://github.com/Cambalab/ns-vue-radio/blob/0ba5f15b1016df26a05a76f3a138628245b79f41/app/components/Home.vue#L5)

**Comment by estefi-prieto** [comment]
To create a keystore, we should consider that we need the passwords for the keystore and the keystore alias

**Comment by sgobotta** [comment]
> The header image is hardcoded, we should consider this, it's currently [here](https://github.com/Cambalab/ns-vue-radio/blob/0ba5f15b1016df26a05a76f3a138628245b79f41/app/components/Home.vue#L5)

Perfect, I've just edited the issue requirements in the Script input sections.

**Comment by sgobotta** [comment]
> To create a keystore, we should consider that we need the passwords for the keystore and the keystore alias

Alright. I've just realised anyone could create their own keystore and build applications with it. Though we should remember that when an application is published to a store with a keystore X, if we later deploy an application with a keystore Y, it will be a different application and **not** an update of the previous one. I think anyone who wants to build multiple radios should consider using different keystores when releasing an **.aab** bundle.
