### ISSUE TITLE
Redesign Navigation bar

### ISSUE THREAD

**Issue by NataliaSuarez** [Cambalab/ns-vue-radio#194]
**Is your feature request related to a problem? Please describe.**
In this moment, the icon and text section has the same color and the name section is unter the icon.

**Describe the solution you'd like**
The active section should paint with active background, the text in default color and icon in active color. The others icons should be inactive color. 

![navbar](https://user-images.githubusercontent.com/19873557/73674226-d1f4c080-468e-11ea-8ce9-ecca297b2bd0.png)

**Describe alternatives you've considered**
The inactive color and name section should be in other colors.

- [ ] Investigate the behavior of the navigation bar. #195
- [ ] Set activeColor parameter for Icon in Navigation Bar. #196
- [ ] Set defaultColor in Navigation Bar. #197
- [ ] Set background color in active element #199
- [ ] Change select behavior in navigation bar. #198
