### ISSUE TITLE
Redisign Live Section

### ISSUE THREAD

**Issue by NataliaSuarez** [Cambalab/ns-vue-radio#201]
**Is your feature request related to a problem? Please describe.**
The problem with this component is the way like the data shows on photo. Also, the component doesnt use the active and default colors and it has a bug with play/pause feature because the pause icon should be a stop icon. 

**Describe the solution you'd like**
The image show displayed with card with a default size. Add the show time and use the colors from config. Delete the image for degrade. Resolve the play/pause bug.

**Describe alternatives you've considered**
The show time is not necessary, it depends the ux because if the show time card size is not accesible we doesnt want it.
The color can be change between primary,default,secondary or active but we want respect the design.

**Additional context**
Design version dark
![Screenshot_20200113-122649_2](https://user-images.githubusercontent.com/19873557/73758993-0f6a5400-474a-11ea-8617-405628f4fbed.png)

Design version default
![Screenshot_20200113-122649_4](https://user-images.githubusercontent.com/19873557/73758995-11ccae00-474a-11ea-85b3-a384c3a9c38f.png)

Issues:

- [ ]  Fix background in Live component #202
- [ ]  Use card for current program #203
- [ ]  Add show time in current program card #204
- [ ]  Change the pause/stop icon #206
- [ ]  Update icons #207
- [ ]  Fix display title show #208
- [ ]  Change to uppercase the message in Live Section #209
