### ISSUE TITLE
Redesign Schedule Section

### ISSUE THREAD

**Issue by NataliaSuarez** [Cambalab/ns-vue-radio#210]
**Is your feature request related to a problem? Please describe.**
The days in navigation are very long and the vertical scroll could be complex and make hard the navigation. Also the show cards are big and the image should be horizontal when the live section needs square image or vertical image size. Additionally, the schedule displays more than one show in screen and for better ux it shows just one show with its info.

**Describe the solution you'd like**
Redesign days navigation, changes it to horizontal and change text for short abbreviation.
Add section name at the top. Change the size card and set in correct place. Investigate the horizontal scroll for shows and the behavior above change the days with scroll, it means when you try scroll in last show the navigation change the day and display the first show of the next day. Also add this feature in schedule.

**Describe alternatives you've considered**
That the scroll change between days.
And it can be vertical like now, and in that case we based in this design:
![Screenshot_20200113-122655_3](https://user-images.githubusercontent.com/19873557/73780860-05f2e300-476e-11ea-9ef7-ad0a743dcefc.png)

**Additional context**
Is neccesary take colors from configuration parameters and also base into design:
![Screenshot_20200113-122655_2](https://user-images.githubusercontent.com/19873557/73780968-376bae80-476e-11ea-8faf-0887fc2f160a.png)

Issues:
- [ ]  Redesign navigation(epic) #211 
     - [ ]  Change navigation days to display horizontal #213 
     - [ ]  Update translations days with short description #214 
     - [ ]  Add active background for selected day in navigation days #215 
     - [ ]  Update colors in navigations bar and take them from config #216 
- [ ]  Add section name at the top #217
- [ ]  Investigate the horizontal scroll and change between days. #231
- [ ]  Add horizontal scroll in schedule #232
- [ ] Update card
     - [ ] Change card size #233
     - [ ] Update display elems -size, icon, colors- in show card #234
