### ISSUE TITLE
Redesign days navigation

### ISSUE THREAD

**Issue by NataliaSuarez** [Cambalab/ns-vue-radio#211]
**Is your feature request related to a problem? Please describe.**
The navigation is a vertiral scroll and it has the same color that the background. Also it has the long text for description days.

**Describe the solution you'd like**
Change navigation days to display horizontal and update translations days with short description for better reading. Also add active background for selected day in navigation days with config parameter color and update all colors in navigations bar.

**Additional context**
Is important think it in relation with schedule because displayed shows depends the day and the we want scrolling and change also day in navigation.

**Issues**
- [ ]  Change navigation days to display horizontal #213
- [ ]  Update translations days with short description #214
- [ ]  Add active background for selected day in navigation days #215
- [ ] Update colors in navigations bar and take them from config #216

**Design**
![Screenshot_20200113-122655_2](https://user-images.githubusercontent.com/19873557/73783681-dbefef80-4772-11ea-94d2-fd26f237fbb5.png)
