### ISSUE TITLE
Redesign Write Us Section

### ISSUE THREAD

**Issue by NataliaSuarez** [Cambalab/ns-vue-radio#218]
**Is your feature request related to a problem? Please describe.**
The contact buttons have different styles and it depends if is via mail or other via. So, we need implement a style for each contact button. Also the icons in buttons are solid and could be more general. 
The description text in section has problems and I could be friendlier for user.
The section style has problems with margins and colors, could be better based in desing.

**Describe the solution you'd like**
Change section description text in translations with shorter text.
Generalize the buttons: parameterize icon, text and actions and use it for send mail and send whatsapp functions.
Fix margin in section and center elements in it. 
Change name section color. 
Change description section color.

**Issues**

- [ ] Change description text translations for Write Us Section. #219 
- [ ] Generalize buttons: parameterize icon, text and actions. #220
- [ ] Replace buttons for custom general button in Write Us Section. #221 
- [ ] Fix margin in section and center elements in it. #222 
- [ ] Change name section color. #223 
- [ ] Change description section color. #224 

**Design**
![Writeus](https://user-images.githubusercontent.com/19873557/74031517-75e0b380-4990-11ea-92dc-0ed381d5b080.png)
