### ISSUE TITLE
Redesign Social Section 

### ISSUE THREAD

**Issue by NataliaSuarez** [Cambalab/ns-vue-radio#226]
**Is your feature request related to a problem? Please describe.**
The share button is not easily identified, which makes it possible to lose the function.
The description doesnt consider the radio's name. 
The social buttons have different styles and it depends the redes that we use. So, we need implement a style for each social button. Also the icons in buttons are solid and could be more general and armonic with the rest of design.

**Describe the solution you'd like**
- [ ] Change description in trasnlations #227 
- [ ] Replace each social button with general button #228 
- [ ] Replace share button with general button #229 
- [ ] Add Name Section in Social Section #230 
- [ ] Change text colors by design recomeded. 

**Additional context**
Is not neccesary use colors in button icons.
