### ISSUE TITLE
Easily customize application identity

### ISSUE THREAD

**Issue by sgobotta** [Cambalab/ns-vue-radio#93]
It would be nice to provide a way to easily customize the application to match client needs. Here we encounter a few problems to solve, and some of them are already kind of prone to work properly. I took a few notes of what needs to be dynamically refactored in a first instance:

+   Splash screen
+   Navigation bar icon colors
+   Social Media buttons: urls and colors
+   Application logo image

We already use a config.js to define sections and social media buttons configuration, though it's not enough to provide a more dynamic customization experience.

What we need to do:

Refactor config.js so that sections are not just a string but an object containing:
+   **name**: the name of the bound component to that section
+   **i18nText**: the i18n property used in that section
+   **icon**: the name of the icon

Then we'd be able to dynamically generate BottomNavigationTab objects and we'd have partially covered the **Navigation bar** item of the list above.

Another issue is that components are hardcoded rendered, asumming every user wants all sections to be rendered. This new feature will break. Therefore I think that we can use the `:is` directive along with the `section.name` value to define which component should be rendered.
Next, every component is shown (or not) inside the GridLayout using the `v-show` directive, that can be solved using the `section.name` value. In fact, that logic can be refactored to a method in Home.vue, like we already do with the `v-if` directive logic.

We have another issue regarding the BottomNavigationBar colors. We need to think about a way to dynamically assign appearance from `config.json`. That is no hard thing to do, we can define a new property, such as:
```js
bottomNavigationBar: {
  activeColor: '',
  inactiveColor: '',
  backgroundColor: ''
}
```
> note: keyLineColor seems to have been deprecated. At least, it doesn't show up in the documentation.

All this look good but, we know we can define colors using the class prop, as shown in [here](https://www.npmjs.com/package/nativescript-bottom-navigation#css-styling). We already do that in _mixins.scss and it would be nice to continue doing.

+   [ ] Propose a way to dynamically assign colors from config.json that matches the ones provided by scss.
In order to do this we'll need to know which colors are available and have them all listed (to generate documentation)

This proposal will completely cover the **Navigation Bar** item from the list above.

+   [ ] Social buttons are already quite dynamic. We only need to generate documentation with all those available iconIds
+   [ ] Logo image: write documentation telling what the proper dimensions are for a logo image.
+   [ ] Write a proposal telling how to dynamically change the splash screen

**Comment by sgobotta** [comment]
Solved in #105
